tareas:
    path: /
    controller: App\Controller\TareasController::index

tareasCrear:
    path: /tareas/crear
    controller: App\Controller\TareasController::crear

tareasGuardar:
    path: /tareas/guardar
    controller: App\Controller\TareasController::guardar
    methods: [POST]

tareasConsultar:
    path: /tareas/consultar/
    controller: App\Controller\TareasController::consultar
    methods: [POST]

tareasEditar:
  path: /tareas/editar/{id}
  controller: App\Controller\TareasController::editar
  defaults: { id: '0' }

tareasEliminar:
  path: /tareas/eliminar/{id}
  controller: App\Controller\TareasController::eliminar
  defaults: { id: '0' }

tareasConsulatarNombres:
  path: /tareas/consultarNombres
  controller: App\Controller\TareasController::consultarNombres
  methods: [POST]

categoriaCrear:
    path: /categoria/crear
    controller: App\Controller\CategoriaController::crear

categoriaGuardar:
    path: /categoria/guardar
    controller: App\Controller\CategoriaController::guardar
    methods: [POST]

categoriaEditar:
    path: /categoria/editar/{id}
    controller: App\Controller\CategoriaController::editar
    defaults: { id: '0' }

categoriaEliminar:
    path: /categoria/eliminar/{id}
    controller: App\Controller\CategoriaController::eliminar
    defaults: { id: '0' }

